apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: MachinePool
metadata:
  name: autoscaling
spec:
  wait: false
  clusterName: "dscott"
  minimumNodesPerZone: 1
  maximumNodesPerZone: 2
  instanceType: m5.xlarge
  labels:
    this: that
