apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: MachinePool
metadata:
  name: sample-missing
spec:
  wait: false
  clusterName: "dscott-test3"
  minimumNodesPerZone: 1
  maximumNodesPerZone: 1
  instanceType: m5.xlarge
  labels:
    owner: dscott
  aws:
    spotInstances:
      enabled: false
