apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: MachinePool
metadata:
  name: override
spec:
  wait: false
  displayName: override-me
  clusterName: "dscott"
  minimumNodesPerZone: 1
  instanceType: m5.xlarge
  aws:
    spotInstances:
      enabled: true
