# permissions for end users to view gitlabidentityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitlabidentityprovider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocm-operator
    app.kubernetes.io/part-of: ocm-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitlabidentityprovider-viewer-role
rules:
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - gitlabidentityproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - gitlabidentityproviders/status
  verbs:
  - get
