# permissions for end users to edit machinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: machinepool-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocm-operator
    app.kubernetes.io/part-of: ocm-operator
    app.kubernetes.io/managed-by: kustomize
  name: machinepool-editor-role
rules:
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - machinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - machinepools/status
  verbs:
  - get
