---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - gitlabidentityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - gitlabidentityproviders/finalizers
  verbs:
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - gitlabidentityproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - ldapidentityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - ldapidentityproviders/finalizers
  verbs:
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - ldapidentityproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - machinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - machinepools/finalizers
  verbs:
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - machinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - rosaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - rosaclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ocm.mobb.redhat.com
  resources:
  - rosaclusters/status
  verbs:
  - get
  - patch
  - update
