apiVersion: ocm.mobb.redhat.com/v1alpha1
kind: ROSACluster
metadata:
  name: rosa-simple
spec:
  accountID: "660250927410"
  displayName: dscott-test3
  tags:
    owner: dscott
  iam:
    userRole: "arn:aws:iam::660250927410:role/ManagedOpenShift-User-dscott_mobb-Role"
  defaultMachinePool:
    minimumNodesPerZone: 2
    instanceType: m5.xlarge
    labels:
      this: that
