---
name: Release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Generate Manifests
        shell: bash
        run: |
          make kustomize

          # generate controller manifests
          mkdir -p build
          cp -r config build
          cd build/config/manager && ../../../bin/kustomize edit set image controller=quay.io/mobb/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}
          ../../../bin/kustomize build ../../default > ../../deploy.yaml

      - name: Login to Quay
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: v1.17.2
          args: release --clean -f ./.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.repository }}
